M48
; DRILL file {KiCad 7.0.5-7.0.5~ubuntu22.04.1} date Thursday 29 June 2023 11:20:05 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-29T11:20:05+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-7.0.5~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X3.56Y-1.94
X3.56Y-4.1
X7.12Y-1.96
X7.12Y-4.12
T0
M30
